contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #oilmining channel"
    url: https://nfcore.slack.com/channels/oilmining
    about: Discussion about the nf-core/oilmining pipeline
